# Generated by Django 3.1.4 on 2021-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('HP', 'Hospedagem'), ('MA', 'E-mail'), ('NV', 'Nuvem')], default='HP', max_length=2, verbose_name='Serviço')),
                ('begin_date', models.DateField(verbose_name='Início do Serviço')),
                ('end_date', models.DateField(verbose_name='Término do Serviço')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
