# Generated by Django 3.1.8 on 2021-06-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210502_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('HP', 'Hospedagem'), ('MA', 'E-mail'), ('HE', 'Hospedagem + E-mail'), ('NV', 'Nuvem')], default='HP', max_length=2, verbose_name='Serviço'),
        ),
    ]
