# Generated by Django 3.1.4 on 2020-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('fone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
