# Generated by Django 3.1.8 on 2021-05-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='responsavel',
            new_name='responsible',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ativo',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
