# Generated by Django 2.0.7 on 2018-07-17 14:46

import afluente.core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', afluente.core.managers.UserManager()),
            ],
        ),
    ]
