# Generated by Django 2.0.7 on 2018-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(max_length=200, null=True, upload_to='clientes/'),
        ),
    ]
