# Generated by Django 2.0.8 on 2018-10-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20181005_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servico',
            field=models.CharField(choices=[('HOSP', 'Hospedagem'), ('MAIL', 'E-mail'), ('HOSMAIL', 'Hospedagem e E-mail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('INT', 'Inativo')], max_length=10),
        ),
    ]
