# Generated by Django 2.0.8 on 2018-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20181016_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(max_length=200, null=True, upload_to='clientes/'),
        ),
    ]
