# Generated by Django 2.0.8 on 2018-11-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20181110_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servico',
            field=models.CharField(choices=[('HOSP', 'Hospedagem'), ('MAIL', 'E-mail'), ('HOSMAIL', 'Hospedagem e E-mail')], max_length=50),
        ),
    ]
